package com.example.nextchat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@CrossOrigin
@Controller // This means that this class is a Controller
@RequestMapping(path="/conv") // This means URL's start with /demo (after Application path)
public class ConversationController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ConversationRepository ConversationRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewConv (@RequestParam String role
            , @RequestParam String content
            ,@RequestParam Integer conv_id) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Conversation n = new Conversation();
        n.setRole(role);
        n.setContent(content);
        n.setConv_id(conv_id);
        ConversationRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Conversation> getAllConv() {
        // This returns a JSON or XML with the users
        return ConversationRepository.findAll();
    }
}