package com.example.nextchat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@CrossOrigin
@Controller // This means that this class is a Controller
@RequestMapping(path="/page") // This means URL's start with /demo (after Application path)
public class PageController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private PageRepository PageRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewPage (@RequestParam String title
            ,@RequestParam Integer conv_id
            ,@RequestParam String maskName) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Page n = new Page();
        n.setTitle(title);
        n.setConv_id(conv_id);
        n.setMaskName(maskName);
        PageRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Page> getAllPages() {
        // This returns a JSON or XML with the users
        return PageRepository.findAll();
    }
}